name: Create Sentry release

on:
  release:
    types: [published, prereleased]

jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: syvita
          SENTRY_PROJECT: miamicoin
          SENTRY_URL: logs.syvita.org
        with:
          version: ${{ github.ref }}
          environment: qa
